# Generated by Django 2.2.8 on 2020-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20181112_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2020-06-29'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Assignment Marks ', 'Assignment Marks'), ('Presentation Marks', 'Presentation Marks'), ('Mid Marks ', 'Mid Marks '), ('Final Theory Marks ', 'Final Theory Marks'), ('Final Pratical Marks', 'Final Pratical Markks'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Assignment Marks ', 'Assignment Marks'), ('Presentation Marks', 'Presentation Marks'), ('Mid Marks ', 'Mid Marks '), ('Final Theory Marks ', 'Final Theory Marks'), ('Final Pratical Marks', 'Final Pratical Markks'), ('Semester End Exam', 'Semester End Exam')], default='Internal test 1', max_length=50),
        ),
    ]
